#!/usr/bin/env python3
"""Generate lib/core/config/google_auth_config.dart from google-services.json.

Extracts the OAuth client whose `client_type` is 3 (the Web client) — the value
that `google_sign_in` 6.x needs as `serverClientId` in order to obtain a Firebase
ID token on Android release builds signed with Play App Signing.

Run this once after cloning the repo and again whenever the active Firebase
project (or its OAuth clients) changes — typically right after
`flutterfire configure` rewrites `google-services.json`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GOOGLE_SERVICES = REPO_ROOT / "android" / "app" / "google-services.json"
OUTPUT = REPO_ROOT / "lib" / "core" / "config" / "google_auth_config.dart"


def find_web_client_id(services: dict) -> str:
    clients = services.get("client") or []
    for client in clients:
        for oauth in client.get("oauth_client", []) or []:
            if oauth.get("client_type") == 3 and oauth.get("client_id"):
                return oauth["client_id"]
    raise SystemExit(
        "No OAuth client with client_type: 3 (Web) found in "
        f"{GOOGLE_SERVICES}. Re-run `flutterfire configure` and ensure a "
        "Web OAuth client exists for the Firebase project."
    )


def main() -> int:
    if not GOOGLE_SERVICES.exists():
        raise SystemExit(f"Missing {GOOGLE_SERVICES}. Run `flutterfire configure` first.")

    services = json.loads(GOOGLE_SERVICES.read_text())
    web_client_id = find_web_client_id(services)
    project_id = services.get("project_info", {}).get("project_id", "")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "// GENERATED FILE. DO NOT EDIT.\n"
        "// Generated by scripts/generate_google_auth_config.py from\n"
        "// android/app/google-services.json.\n"
        "//\n"
        "// Regenerate after `flutterfire configure` or whenever the active\n"
        "// Firebase project changes:\n"
        "//   python3 scripts/generate_google_auth_config.py\n"
        f"// Source Firebase project: {project_id}\n"
        "\n"
        "const String googleWebClientId =\n"
        f"    '{web_client_id}';\n"
    )
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} (project: {project_id})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
