#!/usr/bin/env python3
"""Rename the Android package name (applicationId/namespace) across the project.

Use this when handing off the Flutter project to a different developer/publisher
who will own the Android app under a new applicationId. After running this and
committing the result, the new owner clones the repo and follows the printed
checklist (create their own Firebase project, run `flutterfire configure`, etc.).

Files touched:
  android/app/build.gradle.kts        (namespace + applicationId)
  android/app/src/main/AndroidManifest.xml
  android/app/src/debug/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  android/app/google-services.json    (every package_name field)
  android/app/src/main/kotlin/<old>/  → android/app/src/main/kotlin/<new>/
                                        (move + rewrite package declarations)

Files deliberately NOT touched:
  lib/firebase_options.dart   (regenerated by `flutterfire configure`)
  pubspec.yaml
  ios/                        (iOS bundle ID is a separate concern)

Usage:
  python3 scripts/rename_android_package.py
  python3 scripts/rename_android_package.py --dry-run
  python3 scripts/rename_android_package.py --new-name com.example.app --dry-run
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BUILD_GRADLE = REPO_ROOT / "android" / "app" / "build.gradle.kts"
MAIN_MANIFEST = REPO_ROOT / "android" / "app" / "src" / "main" / "AndroidManifest.xml"
DEBUG_MANIFEST = REPO_ROOT / "android" / "app" / "src" / "debug" / "AndroidManifest.xml"
PROFILE_MANIFEST = REPO_ROOT / "android" / "app" / "src" / "profile" / "AndroidManifest.xml"
GOOGLE_SERVICES = REPO_ROOT / "android" / "app" / "google-services.json"
KOTLIN_ROOT = REPO_ROOT / "android" / "app" / "src" / "main" / "kotlin"

REQUIRED_FILES = [
    BUILD_GRADLE,
    MAIN_MANIFEST,
    DEBUG_MANIFEST,
    PROFILE_MANIFEST,
    GOOGLE_SERVICES,
]

TEXT_REPLACE_TARGETS = [
    BUILD_GRADLE,
    MAIN_MANIFEST,
    DEBUG_MANIFEST,
    PROFILE_MANIFEST,
    GOOGLE_SERVICES,
]

JAVA_KEYWORDS = frozenset({
    "abstract", "assert", "boolean", "break", "byte", "case", "catch",
    "char", "class", "const", "continue", "default", "do", "double",
    "else", "enum", "extends", "final", "finally", "float", "for",
    "goto", "if", "implements", "import", "instanceof", "int",
    "interface", "long", "native", "new", "package", "private",
    "protected", "public", "return", "short", "static", "strictfp",
    "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while",
    "true", "false", "null",
})

SEGMENT_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def validate_package_name(name: str) -> str | None:
    """Return None if valid, else a human-readable error message."""
    if not name:
        return "Package name cannot be empty."
    if name != name.lower():
        return "Must be lowercase."
    if "." not in name:
        return "Must contain at least one dot (e.g., com.example.app)."
    for seg in name.split("."):
        if not seg:
            return "Segments cannot be empty (no leading/trailing/double dots)."
        if not SEGMENT_RE.match(seg):
            return (
                f"Segment '{seg}' is not a valid identifier "
                "(must start with a lowercase letter; only lowercase letters, "
                "digits, and underscores allowed)."
            )
        if seg in JAVA_KEYWORDS:
            return f"Segment '{seg}' is a reserved Java/Kotlin keyword."
    return None


def check_required_files() -> None:
    missing = [p for p in REQUIRED_FILES if not p.exists()]
    if missing:
        lines = ["Missing required file(s); aborting:"]
        for p in missing:
            lines.append(f"  {p}")
        raise SystemExit("\n".join(lines))


def read_current_package() -> str:
    text = BUILD_GRADLE.read_text()
    m = re.search(r'applicationId\s*=\s*"([^"]+)"', text)
    if not m:
        raise SystemExit(
            f"Could not find applicationId in "
            f"{BUILD_GRADLE.relative_to(REPO_ROOT)}"
        )
    return m.group(1)


def find_kotlin_dir(package: str) -> Path:
    return KOTLIN_ROOT.joinpath(*package.split("."))


def replace_in_file(path: Path, old: str, new: str, dry_run: bool) -> int:
    text = path.read_text()
    count = text.count(old)
    if count == 0:
        return 0
    if not dry_run:
        path.write_text(text.replace(old, new))
    return count


def rewrite_kotlin_text(text: str, old: str, new: str) -> str:
    # Rewrite `package <old>` and `package <old>.<sub>...`
    package_re = re.compile(
        rf'^(\s*package\s+){re.escape(old)}(\b|\.)',
        flags=re.MULTILINE,
    )
    text = package_re.sub(
        lambda m: f'{m.group(1)}{new}{m.group(2) if m.group(2) == "." else ""}',
        text,
    )
    # Rewrite `import <old>.<...>`
    import_re = re.compile(
        rf'^(\s*import\s+){re.escape(old)}\.',
        flags=re.MULTILINE,
    )
    text = import_re.sub(lambda m: f'{m.group(1)}{new}.', text)
    return text


def cleanup_empty_dirs(start: Path, stop_at: Path) -> None:
    """Walk up from `start`, removing empty directories until `stop_at` (exclusive)."""
    p = start
    while p != stop_at and stop_at in p.parents:
        try:
            if p.exists() and not any(p.iterdir()):
                p.rmdir()
            else:
                break
        except OSError:
            break
        p = p.parent


def move_kotlin_sources(old: str, new: str, dry_run: bool) -> list[str]:
    old_dir = find_kotlin_dir(old)
    new_dir = find_kotlin_dir(new)
    actions: list[str] = []

    kt_files = sorted(old_dir.rglob("*.kt"))
    if not kt_files:
        actions.append(
            f"(no .kt files found under {old_dir.relative_to(REPO_ROOT)})"
        )

    for kt in kt_files:
        rel_inside = kt.relative_to(old_dir)
        target = new_dir / rel_inside
        text = kt.read_text()
        new_text = rewrite_kotlin_text(text, old, new)
        actions.append(
            f"move: {kt.relative_to(REPO_ROOT)} → {target.relative_to(REPO_ROOT)}"
        )
        if new_text != text:
            actions.append(f"  rewrite package/import declarations ({old} → {new})")
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(new_text)
            kt.unlink()

    if dry_run:
        actions.append(
            f"cleanup: would remove now-empty directories under "
            f"{KOTLIN_ROOT.relative_to(REPO_ROOT)} left by the move"
        )
    else:
        cleanup_empty_dirs(old_dir, KOTLIN_ROOT)

    return actions


def confirm(prompt: str) -> bool:
    try:
        ans = input(prompt).strip().lower()
    except EOFError:
        return False
    return ans in ("y", "yes")


def prompt_new_package() -> str:
    while True:
        try:
            entered = input("New Android package name: ").strip()
        except EOFError:
            raise SystemExit("\nNo input received; aborting.")
        if not entered:
            print("  (empty input) please try again", file=sys.stderr)
            continue
        err = validate_package_name(entered)
        if err:
            print(f"  invalid: {err}", file=sys.stderr)
            continue
        return entered


def print_next_steps(new_package: str) -> None:
    bar = "=" * 72
    print()
    print(bar)
    print("Next steps for the new owner")
    print(bar)
    print()
    print("Local rename complete. After cloning this repo, the new owner must:")
    print()
    print("1. Create a new Firebase project in their own account at "
          "https://console.firebase.google.com")
    print(f"2. Add an Android app to it with package name: {new_package}")
    print("3. Add their debug SHA-1 to that Firebase Android app (get it via:")
    print("   cd android && ./gradlew signingReport)")
    print("4. Run: flutterfire configure")
    print("   - This rewrites google-services.json and firebase_options.dart "
          "with their project's values")
    print("5. Run: flutter pub get")
    print("6. Generate their own upload keystore:")
    print("   keytool -genkey -v -keystore android/upload-keystore.jks "
          "-keyalg RSA -keysize 2048 -validity 10000 -alias upload")
    print("7. Create android/key.properties (gitignored) with their keystore details:")
    print("   storeFile=upload-keystore.jks")
    print("   storePassword=<their store password>")
    print("   keyAlias=upload")
    print("   keyPassword=<their key password>")
    print("8. Create the app in their own Play Console developer account, "
          "enroll in Play App Signing")
    print("9. Run: ./scripts/build_release_aab.sh")
    print("10. Upload the AAB to internal testing in their Play Console")
    print("11. Once enrolled in Play App Signing, copy the App Signing SHA-1 "
          "from Play Console")
    print("    and add it to their Firebase Android app, then re-run "
          "flutterfire configure")
    print("    and rebuild before promoting to production")
    print()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rename the Android package name across project files.",
    )
    parser.add_argument(
        "--new-name",
        help="New Android package name (skips the interactive prompt). "
             "Still validated; in non-dry-run mode you'll still be asked to confirm.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview the changes without modifying any files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    check_required_files()
    current = read_current_package()

    old_kotlin_dir = find_kotlin_dir(current)
    if not old_kotlin_dir.is_dir():
        raise SystemExit(
            f"Expected Kotlin source directory not found: "
            f"{old_kotlin_dir.relative_to(REPO_ROOT)}\n"
            f"The current applicationId ({current}) does not match the on-disk "
            f"Kotlin package layout under {KOTLIN_ROOT.relative_to(REPO_ROOT)}."
        )

    print(f"Current Android package: {current}")

    if args.new_name:
        err = validate_package_name(args.new_name)
        if err:
            raise SystemExit(f"Invalid --new-name: {err}")
        new_package = args.new_name
        print(f"New package (from --new-name): {new_package}")
    else:
        new_package = prompt_new_package()

    if new_package == current:
        print("New package is the same as the current one; no changes needed.")
        return 0

    mode_suffix = " (DRY RUN — no files will be changed)" if args.dry_run else ""
    print()
    print("Rename summary:")
    print(f"  old: {current}")
    print(f"  new: {new_package}")
    print()

    if not args.dry_run:
        if not confirm("Proceed with rename? [y/N]: "):
            print("Aborted; no changes made.")
            return 1

    print(f"Applying changes{mode_suffix}...")
    print()

    print("Text replacements:")
    for path in TEXT_REPLACE_TARGETS:
        n = replace_in_file(path, current, new_package, args.dry_run)
        rel = path.relative_to(REPO_ROOT)
        if n == 0:
            print(f"  {rel}: no occurrences (left unchanged)")
        else:
            print(f"  {rel}: {n} occurrence(s) replaced")

    print()
    print("Kotlin sources:")
    for line in move_kotlin_sources(current, new_package, args.dry_run):
        print(f"  {line}")

    if args.dry_run:
        print()
        print("DRY RUN complete. Re-run without --dry-run to apply.")
        return 0

    print()
    print("Rename complete.")
    print_next_steps(new_package)
    return 0


if __name__ == "__main__":
    sys.exit(main())
